on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: a_normal_comment
        uses: laok233/random-rickroll@v1.1
        with:
          percentage: 100
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
